env:
    es6: true
    node: true
    browser: true
parserOptions:
    ecmaVersion: latest
extends: eslint:recommended
globals:
    checkMount: readonly
    getDir: readonly
    hash_alg: readonly
    ko: readonly
    platform: readonly
    shell: readonly
    version: readonly
    win: readonly
    OCTOPRINT_VIEWMODELS: readonly
rules:
    curly:
        - error
        - all
    brace-style:
        - error
        - 1tbs
    one-var:
        - error
        - never
    prefer-const:
        - error
    eqeqeq:
        - error
        - smart
